name: Cleanup old workflow runs
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  actions: write        # Only this workflow gets write permissions
  contents: read        # Minimal read access

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 10
